const Map<String, String> ar = {
  "Change_Language": "تغيير اللغة",
  "Dark_Mode": "الوضع الداكن",
  "Personal_Settings": "الاعدادات الشخصية",
  "Your_Password": "رقمك السرى",
  "Log_out": "خروج",
  "Home": 'الرئيسية',
  'Categories': 'التصنيفات',
  'Courses': 'الكورسات',
  'Settings': 'الاعدادات',
  'Share': 'نشر',
  'About_Us': "عنا",
  'Courses,Programing,Design,Marketing': 'كورسات-برمجة-تصميم-تسويق',
  'Change_your_password': 'تغيير رقمك السرى',
  'Check_out': 'فحص',
  'Changing_personal_settings': "تغيير اعداداتك الشخصية",
  'Sign up': 'تسجيل',
  "Create an account,It's free": 'قم بإنشاء حسابك,إنه مجانى',
  'Already_have_an_account?': 'بالفعل أمتلك حسابا',
  'Dark_Mode,Language': 'وضع مظلم - اللغة',
  'By_creating_an_account,_you_agree_to': 'بإنشاء حسابك تكون وافقت على',
  'Terms of Application': "شروط التطبيق",
  'Welcome': 'مرحبا',
  'In order to be able to use the application and get the discount coupon, please register':
      'لكى تكون قادر على استخدام التطبيق والحصول على كوبون الخصم ..لابد من التسجيل ',
  'Login to your account': 'ادخل إلى حسابك',
  "Don't have an account?": "لاتمتلك حسابا؟",
  "Login with": 'دخول عبر',
  "Login": 'دخول',
};
